### ISSUE TITLE
Elaborate plz on the 3d making of jpg

### ISSUE THREAD

**Issue by limelect** [TomDannert/Panorama3D#1]
Elaborate plz on making the 3d jpg
I took pictures from google search 3d and i see a LINE !! from 
one side to the other.
How ever your 3d jpg has almost no line to see.
So can we have the steps to make the jpg
If i use a small jpg <>300 the picture is
too big on the display and  not able to see normally.
I see your pictures is big size.
So plz elaborate.

**Comment by TomDannert** [comment]
As i wrote in the Delphi Developers Group in Facebook, you need a 360° squerical image thats normally taken from a 360° Camera. Samsug Gear 360 as example. You cant use a simple Image.
